### ISSUE TITLE
Update Team Descriptions

### ISSUE THREAD

**Issue by Keeeeeeeen** [UniversityRadioYork/201623-site#2]
Team leaders have mentioned that the descriptions of the teams on the website are a bit outdated, these should probably be updated.

**Comment by markspolakovs** [comment]
That data comes from MyRadio, so there’s nothing to do in this codebase:

https://github.com/UniversityRadioYork/myradio-go/blob/685895615da0d567a2e78a3203c54110b190f3e8/team.go#L26

https://github.com/UniversityRadioYork/201623-site/blob/27513a747bebc5ca35e1d9576dbb8be916d79a6b/views/team.tmpl#L50-L52
